models/Todo.py
from db.database import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(80), unique=True, nullable=False)
    is_done = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return '<Todo %r>' % self.task

app.py
from flask import Flask
from routes.todo import todo_route
from db.database import init_db

def create_app():
    app = Flask(__name__)
    app.register_blueprint(todo_route)
    init_db(app)
    return app

if __name__ == "__main__":
    app = create_app()
    app.run(debug=True)

routes/todo.py
from flask import Blueprint, request, redirect, render_template
from models.Todo import Todo
from db.database import db

todo_route = Blueprint('todo_route', __name__)

@todo_route.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        task = request.form['task']
        new_task = Todo(task=task)

        try:
            db.session.add(new_task)
            db.session.commit()
            return redirect('/')
        except:
            return 'There was an issue adding your task'

    else:
        tasks = Todo.query.order_by(Todo.id).all()
        return render_template('index.html', tasks=tasks)

@todo_route.route('/delete/<int:id>')
def delete(id):
    task_to_delete = Todo.query.get_or_404(id)

    try:
        db.session.delete(task_to_delete)
        db.session.commit()
        return redirect('/')
    except:
        return 'There was a problem deleting that task'

@todo_route.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    task = Todo.query.get_or_404(id)

    if request.method == 'POST':
        task.task = request.form['task']
        task.is_done = 'is_done' in request.form

        try:
            db.session.commit()
            return redirect('/')
        except:
            return 'There was an issue updating your task'

    else:
        return render_template('edit_task.html', task=task)

templates/edit_task.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Task</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container">
        <h1 class="text-center">Edit Task</h1>
        <form method="POST">
            <div class="input-group mb-3">
                <input type="text" class="form-control" name="task" value="{{ task.task }}" required>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" name="is_done" {% if task.is_done %}checked{% endif %}>
                <label class="form-check-label" for="is_done">Done</label>
            </div>
            <input class="btn btn-outline-primary" type="submit" value="Update Task">
        </form>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Todo List</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container">
        <h1 class="text-center">Todo List</h1>
        <form method="POST">
            <div class="input-group mb-3">
                <input type="text" class="form-control" name="task" placeholder="New Task" required>
                <div class="input-group-append">
                    <input class="btn btn-outline-primary" type="submit" value="Add Task">
                </div>
            </div>
        </form>
        {% for task in tasks %}
        <div class="alert alert-light" role="alert">
            <span>{{ task.task }}</span>
            <a class="btn btn-outline-info btn-sm" href="{{ url_for('todo_route.update', id=task.id) }}">Edit</a>
            <a class="btn btn-outline-danger btn-sm" href="{{ url_for('todo_route.delete', id=task.id) }}">Delete</a>
        </div>
        {% endfor %}
    </div>
</body>
</html>